[versions]
agp = "8.11.0"
breezeIcons = "v1.1.0"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
testRunner = "1.6.2"
testCore = "1.6.1"
testRules = "1.6.1"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2025.07.00"
material3 = "1.4.0-alpha18"
googleIcons = "1.7.8"
navComposeVersion = "2.9.2"
roomVersion = "2.7.2"
roomTesting = "2.7.2"
ksp = "2.0.21-1.0.25"
dagger-hilt = "2.56.2"
hiltNavigationCompose = "1.2.0"
composeUi = "1.8.3"
airbnbLottie = "6.6.7"
googleServices = "4.4.3"
firebaseBom = "33.16.0"
pluginCrashlyticsVersion = "3.0.4"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
breeze-icons = { module = "com.github.MiguelDK17:Breeze-Icons", version.ref = "breezeIcons" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref="material3" }
androidx-navigation-compose = {group = "androidx.navigation", name = "navigation-compose", version.ref = "navComposeVersion"}
androidx-room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "roomVersion"}
androidx-room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "roomVersion"}
androidx-room-ktx = {group = "androidx.room", name = "room-ktx", version.ref = "roomVersion"}
androidx-room-testing = {group = "androidx.room", name = "room-testing", version.ref = "roomTesting"}
hilt-android = {group = "com.google.dagger", name = "hilt-android", version.ref = "dagger-hilt"}
hilt-compiler = {group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger-hilt"}
androidx-hilt-navigation-compose = {group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose"}
androidx-compose-ui = {group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "composeUi"}
airbnb-android-lottie = {group = "com.airbnb.android", name = "lottie", version.ref="airbnbLottie"}
airbnb-android-lottie-compose = {group = "com.airbnb.android", name = "lottie-compose", version.ref= "airbnbLottie"}
google-firebase-bom = {group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom"}
google-firebase-crashlytics = {group = "com.google.firebase", name = "firebase-crashlytics"}
google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics"}
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "googleIcons"}
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "testCore"}
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules"}







[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt"}
compose-compiler = {id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServices"}
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "pluginCrashlyticsVersion"}

